### ISSUE TITLE
Investigate missing internal loads for stand alone retail when using space type wizard

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-model-articulation-gem#104]
https://unmethours.com/question/73734/space-type-and-construction-set-wizard-no-loads-for-901-2016-retailstandalone/

It appears from screenshots that schedules come but not internal loads. See if I can replicate, and see if impacts other measures like create typical. Also test in 3.4

**Comment by DavidGoldwasser** [comment]
I confirmed that this is a bug, test passes, but resulting model isn't fully populated. The code to fix this is probably in the measure in ext gem. Enhanced tests here, or in ext gem.

Some tests look ok, 

Here are ones that do not have loads
 - empty_seed_test.osm (RetailStandalone 2007)
 - strip_mall_test.osm (RetailStripmall DOE Ref Pre-1980)
 - two_story_bar_test.osm (RetailStandalone 2007)
And here are ones that appear fine
 - lg_off_pre_1980_test.osm
 - med_off_test.osm
 - sm_off_test.osm
 - small_hotel_2007_test.osm
 - super_market_test.osm

**Comment by DavidGoldwasser** [comment]
In the thee tests that plug loads don't work constructions appear fine.

**Comment by DavidGoldwasser** [comment]
For StripMall it is finding the building type, but then failing for all of the space type

[openstudio.standards.Model] <-2> Find objects search criteria returned no results. Search criteria: {"template"=>"DOE Ref Pre-1980", "building_type"=>"RetailStripmall", "space_type"=>"Strip mall - type 1"}. Called from :/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/standards/Standards.Model.rb:1802:in `model_find_object'.

This is method that first gets the space types
`get_space_types_from_building_type(building_type, template, false)`

**Comment by DavidGoldwasser** [comment]
RetailStandalone looks very similar, again for all spaces.

[openstudio.standards.Model] <-2> Find objects search criteria returned no results. Search criteria: {"template"=>"90.1-2007", "building_type"=>"RetailStandalone", "space_type"=>"Back_Space"}. Called from :/ruby/2.7.0/gems/openstudio-standards-0.2.16/lib/openstudio-standards/standards/Standards.Model.rb:1802:in `model_find_object'.

**Comment by DavidGoldwasser** [comment]
Ok, `get_space_types_from_building_type` is in ext gem not standards, and has hard coded space types names. 

https://github.com/NREL/openstudio-extension-gem/blob/develop/lib/openstudio/extension/core/os_lib_model_generation.rb#L599-L607

Maybe space type names changed for those building types

**Comment by DavidGoldwasser** [comment]
Working on this in branch, Confirmed doesn't impact create_bar and create_typical, was related to mapping of building type name when getting space types. I'll add test in ext gem to confirm the fix before I merge it. https://github.com/NREL/openstudio-extension-gem/tree/space_type_names_fix

**Comment by DavidGoldwasser** [comment]
Fix is in ext gem, also found issue with use in 2004 and empty model in standards gem.
https://github.com/NREL/openstudio-standards/issues/1343

Closing here, no commit needed to his repo
