### ISSUE TITLE
Problem with LargeOffice in create_bar with 3.8

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-model-articulation-gem#144]
Oddly didn't have large office test, but Small and Medium are fine. Large has data center. Here is new test
https://github.com/NREL/openstudio-model-articulation-gem/blob/laboratory_test/lib/measures/create_bar_from_doe_building_type_ratios/tests/create_bar_from_doe_building_type_ratios_test.rb#L631-L637

I also tired it with latest version of standards (0.6.3) in place of (0.6.1) that shipped with OpenStudio 3.8.

Here is that line in standards gem
https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/geometry/create_bar.rb#L364

```
 1) Error:
CreateBarFromDOEBuildingTypeRatios_Test#test_smart_perm_mult_lg_off:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create.rb:364:in `block in create_sliced_bar_simple_polygons'
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create.rb:360:in `each'
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create.rb:360:in `create_sliced_bar_simple_polygons'
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create.rb:303:in `block in create_sliced_bar_multi_polygons'
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create.rb:199:in `each'
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create.rb:199:in `each_with_index'
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create.rb:199:in `create_sliced_bar_multi_polygons'
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create_bar.rb:570:in `create_bar'
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create_bar.rb:1151:in `bar_hash_setup_run'
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create_bar.rb:1767:in `create_bar_from_args_and_building_type_hash'
    /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-standards-0.6.3/lib/openstudio-standards/geometry/create_bar.rb:2130:in `create_bar_from_building_type_ratios'
    /Users/dgoldwas/Documents/github/nrel/openstudio-model-articulation-gem/lib/measures/create_bar_from_doe_building_type_ratios/measure.rb:407:in `run'
    lib/measures/create_bar_from_doe_building_type_ratios/tests/create_bar_from_doe_building_type_ratios_test.rb:47:in `apply_measure_to_model'
    lib/measures/create_bar_from_doe_building_type_ratios/tests/create_bar_from_doe_building_type_ratios_test.rb:639:in `test_smart_perm_mult_lg_off'

**Comment by DavidGoldwasser** [comment]
@mdahlhausen Any thoughts on this issue with LargeOffice?

**Comment by DavidGoldwasser** [comment]
Here is possible fix on new branch
https://github.com/NREL/openstudio-model-articulation-gem/commit/6854b79df4ee801ba6d31a5093d15fae243afb58

**Comment by mdahlhausen** [comment]
Fixed by https://github.com/NREL/openstudio-standards/pull/1812

**Comment by mdahlhausen** [comment]
Actual fix for the embedded file system with https://github.com/NREL/openstudio-standards/releases/tag/v0.7.1
