### ISSUE TITLE
create_typical measures fail when basement is used

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-model-articulation-gem#46]
I confirmed this isn't standards or building type specific, and doesn't go away if number of above ground floors are increased. I have set this up on repo, where  it can be re-run to replicate results or test fixes. I tested this in OpenStudio 3.1.0
https://github.com/DavidGoldwasser/osw2osa/blob/bug_testing_pre_bundled/run/workflows/basement/in.osw

Issue may be in standards, but wasn't sure so filed issue here to start with. Could also be in extension gem.

`[09:22:26.600101 ERROR] Found error in state 'os_measures' with message ["862: Infinity not allowed in JSON::/ruby/2.5.0/json/common.rb:286:in `generate'\n:/ruby/2.5.0/json/common.rb:286:in `pretty_generate'\n:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/adapters/output/local.rb:111:in `block in communicate_measure_attributes'\neval:427:in `open'\n:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/adapters/output/local.rb:110:in `communicate_measure_attributes'\n:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/jobs/run_os_measures.rb:75:in `perform'\n:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/run.rb:292:in `step'\n:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/run.rb:234:in `run'\n:/openstudio_cli.rb:971:in `execute'\n:/openstudio_cli.rb:761:in `execute'\n:/openstudio_cli.rb:1755:in `<main>'\neval:175:in `eval'\neval:175:in `require_embedded_absolute'\neval:160:in `block in require_embedded'\neval:154:in `each'\neval:154:in `require_embedded'\neval:113:in `require'\neval:3:in `<main>'"]}
dgoldwas:0:osw2osa$`

**Comment by DavidGoldwasser** [comment]
Closing here, I'm going to file in OS, it got through the measure and failed after that.
